Repository klaytn/klaytn, pull requests merged in 2019-10, with the labels that each got.

#254 SC: Add API for get balance of operators
  console/web3ext/web3ext.go
  node/sc/api_bridge.go
  node/sc/local_backend.go
  node/sc/remote_backend.go
  node/sc/sub_bridge_handler.go
  node/sc/subbridge.go
Labels: dev-branch(v1.2.0)

#267 SC: Add API for get balance of operators #254
  console/web3ext/web3ext.go
  node/sc/api_bridge.go
  node/sc/local_backend.go
  node/sc/remote_backend.go
  node/sc/sub_bridge_handler.go
  node/sc/subbridge.go
Labels: dev-branch-cherry-pick

#268 SC: Add API for getAnchroingTxHashByBlockNumber #257
  console/web3ext/web3ext.go
  node/sc/api_bridge.go
Labels: dev-branch-cherry-pick

#257 SC: Add API for getAnchroingTxHashByBlockNumber
  console/web3ext/web3ext.go
  node/sc/api_bridge.go
Labels: dev-branch(v1.2.0)

#269 SC: Add API for operatorThreshold #265
  console/web3ext/web3ext.go
  node/sc/api_bridge.go
  node/sc/bridge_manager.go
Labels: dev-branch-cherry-pick

#265 SC: Add API for operatorThreshold
  console/web3ext/web3ext.go
  node/sc/api_bridge.go
  node/sc/bridge_manager.go
Labels: dev-branch(v1.2.0)

#260 SC: update tx counting for anchoring
  blockchain/types/anchoring_data.go
  node/sc/bridge_manager_test.go
  node/sc/sub_bridge_handler.go
  node/sc/subbridge.go
Labels: dev-branch(v1.2.0)

#274 SC: update tx counting for anchoring (#260)
  blockchain/types/anchoring_data.go
  node/sc/bridge_manager_test.go
  node/sc/sub_bridge_handler.go
  node/sc/subbridge.go
Labels: dev-branch-cherry-pick

#253 SC: Support Token/KLAY locking feature to prevent request value transfer
  contracts/bridge/Bridge.go
  contracts/bridge/BridgeTokens.sol
  contracts/bridge/BridgeTransferCommon.sol
  contracts/bridge/BridgeTransferERC20.sol
  contracts/bridge/BridgeTransferERC721.sol
  contracts/bridge/BridgeTransferKLAY.sol
  contracts/extbridge/ext_bridge.go
  node/sc/bridge_manager.go
  node/sc/bridge_manager_test.go
  node/sc/bridge_test.go
  node/sc/multi_bridge_test.go
Labels: dev-branch(v1.2.0)

#275 SC: Support Token/KLAY locking feature to prevent request value transfer #253
  contracts/bridge/Bridge.go
  contracts/bridge/BridgeTokens.sol
  contracts/bridge/BridgeTransferCommon.sol
  contracts/bridge/BridgeTransferERC20.sol
  contracts/bridge/BridgeTransferERC721.sol
  contracts/bridge/BridgeTransferKLAY.sol
  contracts/extbridge/ext_bridge.go
  node/sc/bridge_manager.go
  node/sc/bridge_manager_test.go
  node/sc/bridge_test.go
  node/sc/multi_bridge_test.go
Labels: dev-branch-cherry-pick

#276 SC : add GetDecodedAnchroingTx API #259
  api/api_public_transaction_pool.go
  console/jsre/deps/bindata.go
  console/jsre/deps/web3.js
Labels: dev-branch-cherry-pick

#259 SC : add GetDecodedAnchroingTx API
  api/api_public_transaction_pool.go
  console/jsre/deps/bindata.go
  console/jsre/deps/web3.js
Labels: dev-branch(v1.2.0)

#291 Fix a race for the txpool.Content method
  blockchain/tx_pool.go
Labels: issue/bug

#294 SC: add a limit for pending request value transfer events (#285)
  node/sc/bridge_manager.go
Labels: dev-branch-cherry-pick

#293 Fix a race for txpool.Content method (#291)
  blockchain/tx_pool.go
Labels: dev-branch-cherry-pick

#279 SC: APIs for valueTransferOperatorThreshold/RegisterOperator #273
  client/bridge_client.go
  console/web3ext/web3ext.go
  node/sc/api_bridge.go
  node/sc/bridge_manager.go
Labels: dev-branch-cherry-pick

#273 SC: APIs for valueTransferOperatorThreshold/RegisterOperator
  client/bridge_client.go
  console/web3ext/web3ext.go
  node/sc/api_bridge.go
  node/sc/bridge_manager.go
Labels: dev-branch(v1.2.0)

#303 Rename `GetTransactOpts` to `GenerateTransactOpts`
  accounts/abi/bind/backends/simulated.go
  accounts/abi/bind/util.go
  node/sc/api_bridge.go
  node/sc/bridge_accounts.go
  node/sc/bridge_manager.go
  node/sc/bridge_manager_test.go
  node/sc/vt_recovery_test.go
Labels: dev-branch(v1.2.0)

#301 initialize undefined values in callTracer
  node/cn/tracers/internal/tracers/assets.go
  node/cn/tracers/internal/tracers/call_tracer.js
Labels: issue/bug

#256 SC: use atomic.value for proposer in round robin policy
  cmd/utils/nodecmd/genesis_test.go
  consensus/istanbul/validator/default.go
Labels: dev-branch(v1.2.0)

#292 Introduce fee-delegated version of ChainDataAnchoring Tx
  blockchain/types/transaction_signing_test.go
  blockchain/types/tx_internal_data.go
  blockchain/types/tx_internal_data_fee_delegated_chain_data_anchoring.go
  blockchain/types/tx_internal_data_fee_delegated_chain_data_anchoring_with_ratio.go
  blockchain/types/tx_internal_data_rlp_decode_test.go
  blockchain/types/tx_internal_data_sender_hash_test.go
  blockchain/types/tx_internal_data_serializer_test.go
  blockchain/types/tx_internal_rlp_encode_test.go
  tests/account_keytype_test.go
  tests/tx_gas_calculation_test.go
  tests/tx_gas_overflow_test.go
  tests/tx_validation_test.go
Labels: open/reviewing

#312 SC: hot fix for load test
  build/packaging/linux/conf/ksend.conf
  build/packaging/linux/conf/kspnd.conf
  build/rpm/etc/ksend/conf/ksend.conf
  build/rpm/etc/kspnd/conf/kspnd.conf
  contracts/bridge/Bridge.go
  contracts/bridge/BridgeTransferCommon.sol
  contracts/bridge/BridgeTransferERC20.sol
  contracts/bridge/BridgeTransferERC721.sol
  contracts/bridge/BridgeTransferKLAY.sol
  contracts/extbridge/ext_bridge.go
  node/sc/api_bridge.go
  node/sc/bridge_manager.go
  node/sc/bridge_test.go
  node/sc/bridgepool/sorted_map_list.go
  node/sc/local_backend.go
  node/sc/metrics.go
  node/sc/sub_event_handler.go
  node/sc/vt_recovery.go
  node/sc/vt_recovery_test.go
Labels: dev-branch(v1.2.0)

#313 [Cherry-Pick]SC: hot fix for load test #312
  build/packaging/linux/conf/ksend.conf
  build/packaging/linux/conf/kspnd.conf
  build/rpm/etc/ksend/conf/ksend.conf
  build/rpm/etc/kspnd/conf/kspnd.conf
  contracts/bridge/Bridge.go
  contracts/bridge/BridgeTransferCommon.sol
  contracts/bridge/BridgeTransferERC20.sol
  contracts/bridge/BridgeTransferERC721.sol
  contracts/bridge/BridgeTransferKLAY.sol
  contracts/extbridge/ext_bridge.go
  node/sc/api_bridge.go
  node/sc/bridge_manager.go
  node/sc/bridge_test.go
  node/sc/bridgepool/sorted_map_list.go
  node/sc/local_backend.go
  node/sc/metrics.go
  node/sc/sub_event_handler.go
  node/sc/vt_recovery.go
  node/sc/vt_recovery_test.go
Labels: dev-branch-cherry-pick

#315 SC: Clean Log
  node/sc/bridge_manager.go
  node/sc/main_bridge_handler.go
  node/sc/main_event_handler.go
  node/sc/sub_bridge_handler.go
  node/sc/sub_event_handler.go
  node/sc/vt_recovery.go
Labels: dev-branch(v1.2.0)

#311 SC: cherry-pick to dev-branch
  cmd/utils/nodecmd/genesis_test.go
  consensus/istanbul/validator/default.go
  consensus/istanbul/validator/default_test.go
Labels: dev-branch(v1.2.0), dev-branch-cherry-pick

#319 SC: Clean Log #315
  node/sc/bridge_manager.go
  node/sc/main_bridge_handler.go
  node/sc/main_event_handler.go
  node/sc/sub_bridge_handler.go
  node/sc/sub_event_handler.go
  node/sc/vt_recovery.go
Labels: dev-branch-cherry-pick

#339 Panic handling for NewTransactionWithMap
  blockchain/types/transaction.go
Labels: issue/bug
