Repository klaytn/klaytn, pull requests merged in 2019-09, with the labels that each got.

#190 database, blockchain, cn, sc: Read/Write DatabaseVersion
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  node/cn/backend.go
  node/cn/sc_backend.go
  node/sc/mainbridge.go
  node/sc/subbridge.go
  storage/database/db_manager.go
  storage/database/db_manager_test.go
Labels: issue/bug

#236 SC: refactoring mainbridge anchoring data decoding
  blockchain/types/anchoring_data.go
  node/sc/bridge_manager_test.go
  node/sc/main_event_handler.go
  node/sc/sub_bridge_handler.go
Labels: dev-branch(v1.2.0)

#255 SC: update the default genesis with a round-robin policy
  cmd/homi/setup/cmd.go
Labels: dev-branch(v1.2.0)

#262 SC: update the default genesis with a round-robin policy (#255)
  cmd/homi/setup/cmd.go
Labels: dev-branch-cherry-pick

#243 SC: introduce a filtering stride and max pending txs
  accounts/abi/bind/backends/simulated.go
  node/sc/bridge_manager.go
  node/sc/bridge_manager_test.go
  node/sc/local_backend.go
  node/sc/remote_backend.go
  node/sc/subbridge.go
  node/sc/vt_recovery.go
  node/sc/vt_recovery_test.go
Labels: dev-branch(v1.2.0)

#264 SC: introduce a filtering stride and max pending txs (#243)
  accounts/abi/bind/backends/simulated.go
  node/sc/bridge_manager.go
  node/sc/bridge_manager_test.go
  node/sc/local_backend.go
  node/sc/remote_backend.go
  node/sc/subbridge.go
  node/sc/vt_recovery.go
  node/sc/vt_recovery_test.go
Labels: dev-branch-cherry-pick

#266 SC : remove unnecessary code
  client/bridge_client.go
Labels: dev-branch(v1.2.0)

#270 SC : remove unnecessary code #266
  client/bridge_client.go
Labels: dev-branch-cherry-pick
