Repository klaytn/klaytn, pull requests merged in 2021-01, with the labels that each got.

#819 Redis cache sets items asynchronously
  storage/statedb/cache_hybrid_test.go
  storage/statedb/cache_redis.go
  storage/statedb/cache_redis_test.go
Labels: need to merge

#845 Add an option to unlock the genesis account by default
  cmd/homi/docker/service/validator.go
Labels: need to merge

#832 blockchain: first implementation of state prefetcher
  blockchain/blockchain.go
  blockchain/state_prefetcher.go
  blockchain/types.go
  cmd/utils/flaggroup.go
  cmd/utils/flags.go
  cmd/utils/nodecmd/nodeflags.go
  storage/statedb/cache.go
Labels: testing

#850 Limit the number of subscriptions for a websocket connection
  cmd/utils/flags.go
  cmd/utils/nodecmd/nodeflags.go
  console/web3ext/web3ext.go
  networks/rpc/server.go
  networks/rpc/subscription_test.go
  node/utils.go
Labels: docs update needed

#846 Klaytn version up to v1.6.0
  params/version.go
Labels: need to merge

#865 Add chainId API for compatibility with Ethereum (Metamask)
  api/api_public_blockchain.go
  console/jsre/deps/web3.js
Labels: need to merge

#866 Add flags for websocket read/write deadlines
  cmd/utils/flags.go
  cmd/utils/nodecmd/nodeflags.go
  networks/rpc/server.go
  networks/rpc/websocket.go
Labels: need to merge

#868 Use default enpoints for DynamoDB and S3
  storage/database/dynamodb.go
Labels: need to merge

#860 blockchain: improve StatePrefetcher by prefetching txs when fetcher works
  blockchain/blockchain.go
  blockchain/state_prefetcher.go
  blockchain/types.go
Labels: need to merge

#871 Remove darwin/386 in cross compile scripts
  build/cross-compile.sh
  build/package-tar.sh
Labels: need to merge

#861 rpc: replace big.Int to hexutil.Big for RPC handling
  api/api_public_blockchain.go
  api/api_public_klay.go
  governance/api.go
  networks/rpc/json.go
  networks/rpc/server.go
  networks/rpc/utils.go
Labels: need to merge

#862 Limit the number of websocket connections and added metrics
  cmd/utils/flags.go
  cmd/utils/nodecmd/nodeflags.go
  networks/rpc/metrics.go
  networks/rpc/server.go
  networks/rpc/types.go
  networks/rpc/websocket.go
  networks/rpc/websocket_test.go
Labels: need to merge

#872 Move blockchain waitgroup control in migrateState
  blockchain/state_migration.go
Labels: need to merge

#881 state: properly reset static variable stateObjEncoder
  blockchain/state/state_object_encoder.go
  blockchain/state/state_object_encoder_test.go
Labels: need to merge
