Repository klaytn/klaytn, pull requests merged in 2021-03, with the labels that each got.

#901 params, blockchain/vm: rename hardfork name, Incompatible1 to IstanbulCompatible
  blockchain/vm/contracts.go
  blockchain/vm/contracts_test.go
  blockchain/vm/evm.go
  blockchain/vm/internaltx_tracer.go
  blockchain/vm/jump_table.go
  node/cn/tracers/tracer.go
  params/config.go
Labels: docs update needed

#891 Fix invalid validator list in extraData of block header
  consensus/istanbul/backend/api.go
  consensus/istanbul/backend/engine.go
  tests/klay_test_blockchain_test.go
  work/worker.go
Labels: issue/bug, need to merge

#933 Set chain of Istanbul backend when the fake worker is enabled
  consensus/consensus.go
  consensus/istanbul/backend/engine.go
  node/cn/backend.go
Labels: issue/bug
