Repository klaytn/klaytn, pull requests merged in 2021-07, with the labels that each got.

#1010 blake2b: apply additional blake2b implementation
  crypto/blake2b/blake2b_f_fuzz.go
  crypto/blake2b/blake2b_f_test.go
  crypto/blake2b/blake2b_ref.go
Labels: istanbul-compatible

#996 blockchain/vm: sstore gas cost change (eip2200)
  blockchain/state/statedb.go
  blockchain/vm/eips.go
  blockchain/vm/gas_table.go
  blockchain/vm/gas_table_test.go
  blockchain/vm/interface.go
  blockchain/vm/interpreter.go
  blockchain/vm/jump_table.go
  params/protocol_params.go
  tests/state_test_util.go
Labels: backward incompatible, docs update needed, istanbul-compatible

#1011 blockchain: do nothing if nil stateDB is returned for prefetcher
  blockchain/blockchain.go
Labels: need to merge

#992 command options: Add dumpgenesis command
  cmd/kcn/main.go
  cmd/ken/main.go
  cmd/kpn/main.go
  cmd/kscn/main.go
  cmd/ksen/main.go
  cmd/kspn/main.go
  cmd/utils/flags.go
  cmd/utils/nodecmd/chaincmd.go
Labels: need to merge

#1008 Implemented error callback and expiration of message
  datasync/chaindatafetcher/kafka/config.go
  datasync/chaindatafetcher/kafka/consumer.go
  datasync/chaindatafetcher/kafka/consumer_test.go
  datasync/chaindatafetcher/kafka/kafka_test.go
Labels: need to merge

#1009 blockchain: make chainConfig updatable by using hard-coded chainConfigs
  blockchain/genesis.go
  governance/default_test.go
  params/config.go
Labels: istanbul-compatible, need to merge

#997 consensus/istanbul: add round to previous hash
  blockchain/types/tx_internal_data_legacy.go
  consensus/istanbul/backend/backend_test.go
  consensus/istanbul/backend/engine_test.go
  consensus/istanbul/core/commit_test.go
  consensus/istanbul/core/handler_test.go
  consensus/istanbul/core/prepare_test.go
  consensus/istanbul/validator/default.go
  consensus/istanbul/validator/default_test.go
  consensus/istanbul/validator/weighted.go
  consensus/istanbul/validator/weighted_random_test.go
  fork/fork.go
  log/log_modules.go
Labels: backward incompatible, istanbul-compatible, need to merge

#1001 blockchain/types: multisig improvement
  blockchain/types/accountkey/account_key.go
  blockchain/types/accountkey/account_key_fail.go
  blockchain/types/accountkey/account_key_legacy.go
  blockchain/types/accountkey/account_key_nil.go
  blockchain/types/accountkey/account_key_public.go
  blockchain/types/accountkey/account_key_role_based.go
  blockchain/types/accountkey/account_key_test.go
  blockchain/types/accountkey/account_key_weighted_multi_sig.go
  blockchain/types/transaction.go
  blockchain/vm/contracts.go
  blockchain/vm/contracts_test.go
Labels: backward incompatible, istanbul-compatible, need to merge
